server:
  port: 9001
mysql-cdc-es:
  infos:
  ip: 127.0.0.1
  port: 3306
  dbs: user
  user: root
  pwd: 1234qwer
  tables: user.system_dept
spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic



